# Generated by Django 5.2.1 on 2025-05-13 15:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import admin_modules.core.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('title', models.CharField(max_length=255)),
                ('params', models.JSONField(blank=True, null=True)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('pdf_key', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='DRAFT', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
