# Generated by Django 5.2.1 on 2025-05-13 15:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import admin_modules.core.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('ml_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('class_code', models.SmallIntegerField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('mask_key', models.CharField(max_length=512)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('severity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('source', models.CharField(default='model', max_length=50)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='media.image')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='ml_models.mlmodel')),
            ],
            options={
                'db_table': 'defect',
            },
        ),
        migrations.CreateModel(
            name='DefectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('version', models.IntegerField()),
                ('payload', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_versions', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='defects.defect')),
            ],
            options={
                'db_table': 'defect_version',
                'ordering': ['-version'],
                'unique_together': {('defect', 'version')},
            },
        ),
    ]
