# Generated by Django 5.2.1 on 2025-05-09 17:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("media", "__first__"),
        ("ml_models", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("class_code", models.SmallIntegerField()),
                ("bbox_x1", models.FloatField()),
                ("bbox_y1", models.FloatField()),
                ("bbox_x2", models.FloatField()),
                ("bbox_y2", models.FloatField()),
                ("mask_key", models.CharField(max_length=512)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("severity", models.DecimalField(decimal_places=2, max_digits=4)),
                ("source", models.CharField(default="model", max_length=50)),
                ("last_version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="media.image",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defects",
                        to="ml_models.modelentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefectVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField()),
                ("payload", models.JSONField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defect_versions",
                        to="authentication.user",
                    ),
                ),
                (
                    "defect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="defects.defect",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("defect", "version")},
            },
        ),
    ]
