# Generated by Django 5.2.1 on 2025-05-19 20:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='bbox_x1',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='bbox_x2',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='bbox_y1',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='bbox_y2',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='source',
        ),
        migrations.AddField(
            model_name='defect',
            name='polygon_full',
            field=models.JSONField(help_text='Координаты относительно всей ленты', null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='polygon_tile',
            field=models.JSONField(help_text='Координаты относительно тайла', null=True),
        ),
    ]
