# Generated by Django 5.2.1 on 2025-05-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_remove_defect_bbox_x1_remove_defect_bbox_x2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='model',
        ),
    ]
