# Generated by Django 5.2.1 on 2025-05-11 12:16

import uuid

from django.db import migrations
from django.db import models

import admin_modules.core.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [ # type: ignore
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('name', models.CharField(max_length=255)),
                ('git_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('training_set', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ml_model',
            },
        ),
    ]
