# Generated by Django 5.2.1 on 2025-05-11 12:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import admin_modules.core.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('file_key', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('width_px', models.IntegerField(blank=True, null=True)),
                ('height_px', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_upload', 'Ожидает загрузки'), ('uploaded', 'Загружено'), ('upload_error', 'Ошибка загрузки'), ('processing', 'В обработке'), ('processed', 'Обработка завершена'), ('annotation_pending', 'Готово к разметке'), ('annotating', 'В процессе разметки'), ('annotated', 'Разметка завершена'), ('review_pending', 'Ждёт верификации'), ('reviewed', 'Верифицировано'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'Архивировано'), ('error', 'Ошибка')], default='pending_upload', max_length=50)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
