# Generated by Django 5.2.1 on 2025-05-09 17:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_key", models.CharField(max_length=512, unique=True)),
                ("original_filename", models.CharField(blank=True, max_length=512)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("width_px", models.IntegerField(blank=True, null=True)),
                ("height_px", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_images",
                        to="authentication.user",
                    ),
                ),
            ],
        ),
    ]
