# Generated by Django 5.2.1 on 2025-05-13 15:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import admin_modules.core.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('multipart_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('init', 'Init'), ('success', 'Success'), ('error', 'Error')], default='init', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_session',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('file_key', models.CharField(max_length=512, unique=True)),
                ('width_px', models.IntegerField(blank=True, null=True)),
                ('height_px', models.IntegerField(blank=True, null=True)),
                ('original_size', models.BigIntegerField(blank=True, null=True)),
                ('original_checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('process_pending', 'Proccess Pending'), ('processing', 'В обработке'), ('processed', 'Обработка завершена'), ('annotation_pending', 'Готово к разметке'), ('annotating', 'В процессе разметки'), ('annotated', 'Разметка завершена'), ('review_pending', 'Ждёт верификации'), ('reviewed', 'Верифицировано'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'Архивировано'), ('error', 'Ошибка')], default='process_pending', max_length=50)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.uploadsession')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
