# Generated by Django 5.2.1 on 2025-05-11 13:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
