# Generated by Django 5.2.1 on 2025-05-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='session',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_checksum',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_size',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('process_pending', 'Готово к обработке'), ('processing', 'В обработке'), ('processed', 'Обработка завершена'), ('annotation_pending', 'Готово к разметке'), ('annotating', 'В процессе разметки'), ('annotated', 'Разметка завершена'), ('review_pending', 'Ждёт верификации'), ('reviewed', 'Верифицировано'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'Архивировано'), ('error', 'Ошибка')], default='process_pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='UploadSession',
        ),
    ]
