# Generated by Django 5.2.1 on 2025-05-11 14:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import admin_modules.core.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_image_original_checksum_image_original_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='original_checksum',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('process_pending', 'Proccess Pending'), ('processing', 'В обработке'), ('processed', 'Обработка завершена'), ('annotation_pending', 'Готово к разметке'), ('annotating', 'В процессе разметки'), ('annotated', 'Разметка завершена'), ('review_pending', 'Ждёт верификации'), ('reviewed', 'Верифицировано'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'Архивировано'), ('error', 'Ошибка')], default='process_pending', max_length=50),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=admin_modules.core.models.mixins.local_time)),
                ('filename', models.CharField(max_length=255)),
                ('expected_size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('multipart_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('init', 'Init'), ('success', 'Success'), ('error', 'Error')], default='init', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_session',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.uploadsession'),
        ),
    ]
