# Generated by Django 5.2.1 on 2025-05-11 20:10

from django.db import migrations
from django.db import models

import admin_modules.core.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_image_original_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='original_checksum',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='created_at',
            field=models.DateTimeField(default=admin_modules.core.models.mixins.local_time),
        ),
    ]
