# Generated by Django 5.2.1 on 2025-05-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_image_is_verified_image_original_checksum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='expected_size',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='sha256',
        ),
    ]
